server:
  port: 8989


turbine:
  aggregator:
    clusterConfig: READ
  appConfig: READ

logging:
  level: INFO
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/